[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "solarathon"
description = "Template project for Solarathon 2023"
version = "0.0.1"
dependencies = [
    "solara==1.23.0",
]

[project.optional-dependencies]
dev = [
    "mypy",
]

[tool.hatch.build]
include = [
  "**/*.css",
  "**/*.py",
]
