# based on https://docs.cloud.ploomber.io/en/latest/user-guide/github.html
name: Ingestion and Deployment Pipeline

on:
  push:
    branches:
      # only deploy from the ploomber branch
      - ploomber_dev

jobs:
  deploy-to-ploomber-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Fetch Initial Discord Messages
        env:
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/discord_pipeline/requirements.txt
          python backend/discord_pipeline/get_messages.py

      - name: Run Haystack pipeline Step 1 and Step 2
        env:
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          tree . 

          pip install -r backend/haystack_pipeline/requirements.txt
          python backend/haystack_pipeline/step_1_generate_faqs.py

          python backend/haystack_pipeline/step_2_indexing.py

          tree .

      - name: Deploy
        env:
          PLOOMBER_CLOUD_KEY: ${{ secrets.PLOOMBER_CLOUD_KEY_S }}
        run: |
          (cd ploomber && ploomber-cloud deploy)